# -*- coding: utf-8 -*-
"""
Generate the paper's tables from the code tables themselves.

    python make_paper_tables.py

Writes paper/generated.tex.

Nothing in the paper's data is typed by hand. The alphabet table, the shared-cell
table and the verification figures all come out of the same modules the software
runs on, so the paper cannot drift away from the thing it describes. If a cell
changes in sindhi_braille.py, it changes in the paper at the next compile.
"""
import io, os, sys, collections, contextlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TOOLS = os.path.join(ROOT, 'tools')
sys.path.insert(0, TOOLS)
import sindhi_braille as sb
import make_ambiguity as amb
import check_all


def cell(dots):
    r"""\bcell{1,3} -- the paper draws every cell from its dot numbers, so the
    braille in the paper is drawn by the same numbers the embosser receives."""
    return r'\bcell{%s}' % ','.join(dots)


SCRIPT = set(range(0x0600, 0x0700)) | set(range(0x0750, 0x0780)) \
       | set(range(0xFB50, 0xFE00)) | set(range(0xFE70, 0xFF00))


def esc(s):
    for a, b in (('&', r'\&'), ('%', r'\%'), ('#', r'\#'), ('_', r'\_')):
        s = s.replace(a, b)
    return s


def sd(s):
    r"""Wrap every run of Sindhi script in \sd, so the Latin face is never asked
    for a letter it does not have. A table of Sindhi letters typeset in Latin
    Modern is a table of blanks, and LaTeX says so only in the log."""
    out, run = [], []
    for ch in s:
        if ord(ch) in SCRIPT:
            run.append(ch)
        else:
            if run: out.append(r'\sd{%s}' % ''.join(run)); run = []
            out.append(ch)
    if run: out.append(r'\sd{%s}' % ''.join(run))
    return ''.join(out)


def how_map():
    """The 'how it is decided' column, read out of the website source so that
    the paper and the site say the same thing about the same cell."""
    import re
    src = io.open(os.path.join(ROOT, 'website', 'src', 'page.html'),
                  encoding='utf-8').read()
    out = {}
    for m in re.finditer(r"'(\d+)'\s*:\s*\['((?:[^'\\\\]|\\\\.)*)'", src):
        txt = m.group(2)
        txt = re.sub(r'</?strong>', '', txt)
        out.setdefault(m.group(1), txt)
    fb = re.search(r"const FALLBACK\s*=\s*\['([^']*)'", src)
    out['__fallback__'] = fb.group(1) if fb else ''
    return out


# ---- 1. the alphabet ------------------------------------------------------
def alphabet():
    rows = []
    for ch, cs in sb.LETTER.items():
        rows.append((ch, ' '.join(cell(c) for c in cs), ' '.join(cs)))
    out = [r'% generated by make_paper_tables.py -- do not edit',
           r'\begin{LTR}',
           r'\begin{longtable}{llll llll}',
           r'\toprule']
    per = 4
    body = []
    for i in range(0, len(rows), per):
        chunk = rows[i:i + per]
        body.append(' & '.join('\\sd{%s} & %s' % (c, b) for c, b, _ in chunk)
                    + (' & ' * (2 * (per - len(chunk)))) + r' \\')
    out += body + [r'\bottomrule', r'\end{longtable}', r'\end{LTR}']
    return '\n'.join(out), len(rows)


# ---- 2. the cells that carry more than one reading ------------------------
def ambiguity():
    tbl = amb.table()
    how = how_map()
    lines = [r'% generated by make_paper_tables.py -- do not edit',
             r'\begin{LTR}\footnotesize',
             r'\begin{longtable}{clp{0.31\linewidth}p{0.34\linewidth}}',
             r'\caption{Every cell the code assigns more than one reading, with '
             r'the criterion that resolves it. Generated from the implemented '
             r'tables.}\label{tab:ambiguity}\\',
             r'\toprule',
             r'cell & dots & readings & resolved by \\',
             r'\midrule\endhead']
    for row in tbl:
        reads = '; '.join(sd(esc(r[0])) for r in row['readings'])
        lines.append(r'%s & \texttt{%s} & %s & %s \\[2pt]' %
                     (cell(row['cell']), row['cell'], reads,
                      sd(esc(how.get(row['cell']) or how.get('__fallback__', '')))))
    lines += [r'\bottomrule', r'\end{longtable}', r'\end{LTR}']
    return '\n'.join(lines), len(tbl), sum(1 for r in tbl if r['n'] >= 3)


# ---- 3. what the verification suite actually reports -----------------------
def verification():
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        check_all.main()
    rows = []
    for name, ok, detail in check_all.results:
        mark = {True: r'\pass', False: r'\fail', None: r'\skipped'}[ok]
        rows.append(r'%s & \texttt{%s} & %s \\' % (mark, name, sd(esc(detail))))
    lines = [r'% generated by make_paper_tables.py -- do not edit',
             r'\begin{LTR}\small',
             r'\begin{tabular}{llp{0.60\linewidth}}',
             r'\toprule', r' & check & what it reports \\', r'\midrule']
    lines += rows
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{LTR}']
    passed = sum(1 for _, ok, _ in check_all.results if ok is True)
    return '\n'.join(lines), passed, len(check_all.results)


# ---- 4. how many meanings the code assigns to single cells ----------------
def counts():
    """The same universe the shared-cell table is drawn from, so the count and
    the table cannot disagree: every mark that stands as one cell on its own."""
    use = amb.all_readings()
    meanings = sum(len(v) for v in use.values())
    return meanings, len(use)


def histogram():
    """How many meanings each cell carries. Same universe as the shared-cell
    table, so the picture and the table cannot disagree."""
    import collections
    use = amb.all_readings()
    c = collections.Counter(len(v) for v in use.values())
    mx = max(c.values())
    bars = []
    for k in sorted(c):
        h = 3.4 * c[k] / mx
        bars.append(r'\draw[fill=black!72, draw=none] (%d-0.32,0) rectangle (%d+0.32,%.3f);'
                    % (k, k, h))
        bars.append(r'\node[font=\scriptsize, anchor=south] at (%d,%.3f) {%d};'
                    % (k, h, c[k]))
    lines = [r'\newcommand{\ReadingsHistogram}{%',
             r'\begin{tikzpicture}[x=13mm, y=9mm]',
             r'\draw[black!40] (0.4,0) -- (%.1f,0);' % (max(c) + 0.6)] + bars + [
             r'\foreach \k in {1,...,%d}{\node[font=\small, anchor=north] at (\k,-0.08) {\k};}' % max(c),
             r'\node[font=\small, anchor=north] at (%.1f,-0.75) {meanings carried by one cell};' % ((1 + max(c)) / 2.0),
             r'\node[font=\small, rotate=90, anchor=south] at (0.25,1.7) {cells};',
             r'\end{tikzpicture}}']
    return '\n'.join(lines)


def worked():
    """One sentence carried all the way through, as Figure 4.

    It is chosen because it fires four different rules at once: a sign written
    out as a word, the number sign, a comparison sign closed up to the number
    after it, and the one cell whose reading no position can settle."""
    sb.load_words()
    text = 'هن ۾ 8 + 9 = 17 آهي؟'
    lines = sb.translate(text)
    groups = lines[0]
    back = sb.back(lines)
    cols = []
    for g in groups:
        cols.append((' '.join(cell(c) for c in g), ' '.join(g)))
    body = []
    # sd() wraps only the runs of Sindhi script; the digits and the + and =
    # in this sentence must stay in the Latin face, which has them.
    body.append(r'\newcommand{\WorkedSindhi}{%s}' % sd(text))
    body.append(r'\newcommand{\WorkedBack}{%s}' % sd(back))
    body.append(r'\newcommand{\WorkedGroups}{%')
    body.append(r'\begin{tabular}{%s}' % ('c' * len(cols)))
    body.append(' & '.join(c for c, _ in cols) + r' \\[3pt]')
    body.append(' & '.join(r'{\scriptsize\ttfamily %s}' % d.replace(' ', r'\,')
                           for _, d in cols) + r' \\')
    body.append(r'\end{tabular}}')
    return '\n'.join(body), len(groups)


def main():
    alpha, nletters = alphabet()
    ambt, nshared, nthree = ambiguity()
    vert, npass, nchecks = verification()
    meanings, cells_used = counts()

    hist = histogram()
    work, ngroups = worked()

    macros = [
        r'% ---- figures, generated -------------------------------------------',
        r'\newcommand{\NLetters}{%d}' % nletters,
        r'\newcommand{\NMeanings}{%d}' % meanings,
        r'\newcommand{\NCellsUsed}{%d}' % cells_used,
        r'\newcommand{\NCellsTotal}{63}',
        r'\newcommand{\NShared}{%d}' % nshared,
        r'\newcommand{\NThreeWay}{%d}' % nthree,
        r'\newcommand{\NChecks}{%d}' % nchecks,
        r'\newcommand{\NChecksPassed}{%d}' % npass,
        '',
        r'\newcommand{\AlphabetTable}{%' + '\n' + alpha + '\n}',
        '',
        r'\newcommand{\AmbiguityTable}{%' + '\n' + ambt + '\n}',
        '',
        r'\newcommand{\VerificationTable}{%' + '\n' + vert + '\n}',
        '',
        hist,
        '',
        work,
        r'\newcommand{\NWorkedGroups}{%d}' % ngroups,
    ]
    out = os.path.join(HERE, 'generated.tex')
    io.open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(macros) + '\n')
    print('generated.tex written')
    print('  %d letters, %d meanings across %d cells, %d shared, %d three-way'
          % (nletters, meanings, cells_used, nshared, nthree))
    print('  %d of %d checks passed' % (npass, nchecks))


if __name__ == '__main__':
    main()
