# -*- coding: utf-8 -*-
"""
Generate the paper's tables from the code tables themselves.

    python make_paper_tables.py

Writes paper/generated.tex.

Nothing in the paper's data is typed by hand. The alphabet table, the shared-cell
table and the verification figures all come out of the same modules the software
runs on, so the paper cannot drift away from the thing it describes. If a cell
changes in sindhi_braille.py, it changes in the paper at the next compile.
"""
import io, os, sys, collections, contextlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TOOLS = os.path.join(ROOT, 'tools')
sys.path.insert(0, TOOLS)
import sindhi_braille as sb
import make_ambiguity as amb
import check_all


def cell(dots):
    r"""\bcell{1,3} -- the paper draws every cell from its dot numbers, so the
    braille in the paper is drawn by the same numbers the embosser receives."""
    return r'\bcell{%s}' % ','.join(dots)


SCRIPT = set(range(0x0600, 0x0700)) | set(range(0x0750, 0x0780)) \
       | set(range(0xFB50, 0xFE00)) | set(range(0xFE70, 0xFF00))


def esc(s):
    for a, b in (('&', r'\&'), ('%', r'\%'), ('#', r'\#'), ('_', r'\_')):
        s = s.replace(a, b)
    return s


def sd(s):
    r"""Wrap every run of Sindhi script in \sd, so the Latin face is never asked
    for a letter it does not have. A table of Sindhi letters typeset in Latin
    Modern is a table of blanks, and LaTeX says so only in the log."""
    out, run = [], []
    for ch in s:
        if ord(ch) in SCRIPT:
            run.append(ch)
        else:
            if run: out.append(r'\sd{%s}' % ''.join(run)); run = []
            out.append(ch)
    if run: out.append(r'\sd{%s}' % ''.join(run))
    return ''.join(out)


def how_map():
    """The 'how it is decided' column, read out of the website source so that
    the paper and the site say the same thing about the same cell."""
    import re
    src = io.open(os.path.join(ROOT, 'website', 'src', 'page.html'),
                  encoding='utf-8').read()
    out = {}
    for m in re.finditer(r"'(\d+)'\s*:\s*\['((?:[^'\\\\]|\\\\.)*)'", src):
        txt = m.group(2)
        txt = re.sub(r'</?strong>', '', txt)
        out.setdefault(m.group(1), txt)
    return out


# ---- 1. the alphabet ------------------------------------------------------
def alphabet():
    rows = []
    for ch, cs in sb.LETTER.items():
        rows.append((ch, ' '.join(cell(c) for c in cs), ' '.join(cs)))
    out = [r'% generated by make_paper_tables.py -- do not edit',
           r'\begin{LTR}',
           r'\begin{longtable}{llll llll}',
           r'\toprule']
    per = 4
    body = []
    for i in range(0, len(rows), per):
        chunk = rows[i:i + per]
        body.append(' & '.join('\\sd{%s} & %s' % (c, b) for c, b, _ in chunk)
                    + (' & ' * (2 * (per - len(chunk)))) + r' \\')
    out += body + [r'\bottomrule', r'\end{longtable}', r'\end{LTR}']
    return '\n'.join(out), len(rows)


# ---- 2. the cells that carry more than one reading ------------------------
def ambiguity():
    tbl = amb.table()
    how = how_map()
    lines = [r'% generated by make_paper_tables.py -- do not edit',
             r'\begin{LTR}\footnotesize',
             r'\begin{longtable}{clp{0.31\linewidth}p{0.34\linewidth}}',
             r'\toprule',
             r'cell & dots & readings & resolved by \\',
             r'\midrule\endhead']
    for row in tbl:
        reads = '; '.join(sd(esc(r[0])) for r in row['readings'])
        lines.append(r'%s & \texttt{%s} & %s & %s \\[2pt]' %
                     (cell(row['cell']), row['cell'], reads,
                      sd(esc(how.get(row['cell'], '')))))
    lines += [r'\bottomrule', r'\end{longtable}', r'\end{LTR}']
    return '\n'.join(lines), len(tbl), sum(1 for r in tbl if r['n'] >= 3)


# ---- 3. what the verification suite actually reports -----------------------
def verification():
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        check_all.main()
    rows = []
    for name, ok, detail in check_all.results:
        mark = {True: r'\pass', False: r'\fail', None: r'\skipped'}[ok]
        rows.append(r'%s & \texttt{%s} & %s \\' % (mark, name, sd(esc(detail))))
    lines = [r'% generated by make_paper_tables.py -- do not edit',
             r'\begin{LTR}\small',
             r'\begin{tabular}{llp{0.60\linewidth}}',
             r'\toprule', r' & check & what it reports \\', r'\midrule']
    lines += rows
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{LTR}']
    passed = sum(1 for _, ok, _ in check_all.results if ok is True)
    return '\n'.join(lines), passed, len(check_all.results)


# ---- 4. how many meanings the code assigns to single cells ----------------
def counts():
    """The same universe the shared-cell table is drawn from, so the count and
    the table cannot disagree: every mark that stands as one cell on its own."""
    use = amb.all_readings()
    meanings = sum(len(v) for v in use.values())
    return meanings, len(use)


def main():
    alpha, nletters = alphabet()
    ambt, nshared, nthree = ambiguity()
    vert, npass, nchecks = verification()
    meanings, cells_used = counts()

    macros = [
        r'% ---- figures, generated -------------------------------------------',
        r'\newcommand{\NLetters}{%d}' % nletters,
        r'\newcommand{\NMeanings}{%d}' % meanings,
        r'\newcommand{\NCellsUsed}{%d}' % cells_used,
        r'\newcommand{\NCellsTotal}{63}',
        r'\newcommand{\NShared}{%d}' % nshared,
        r'\newcommand{\NThreeWay}{%d}' % nthree,
        r'\newcommand{\NChecks}{%d}' % nchecks,
        r'\newcommand{\NChecksPassed}{%d}' % npass,
        '',
        r'\newcommand{\AlphabetTable}{%' + '\n' + alpha + '\n}',
        '',
        r'\newcommand{\AmbiguityTable}{%' + '\n' + ambt + '\n}',
        '',
        r'\newcommand{\VerificationTable}{%' + '\n' + vert + '\n}',
    ]
    out = os.path.join(HERE, 'generated.tex')
    io.open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(macros) + '\n')
    print('generated.tex written')
    print('  %d letters, %d meanings across %d cells, %d shared, %d three-way'
          % (nletters, meanings, cells_used, nshared, nthree))
    print('  %d of %d checks passed' % (npass, nchecks))


if __name__ == '__main__':
    main()
